const data = [
  {
    id: 1,
    title: "tag to wear",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now"],
    brand: null,
    images: [require("../assets/images/products/1.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 2,
    title: "tag to wear",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now", "top picks"],
    brand: null,
    images: [require("../assets/images/products/2.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 3,
    title: "Blue Denim Jacket",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["top rated", "featured products", "top picks"],
    brand: null,
    images: [require("../assets/images/products/3.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 4,
    title: "tag to wear",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["top rated"],
    brand: null,
    images: [require("../assets/images/products/4.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 5,
    title: "Blue Denim Jacket",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now"],
    brand: null,
    images: [require("../assets/images/products/5.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 6,
    title: "Blue Denim Jacket",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now"],
    brand: null,
    images: [require("../assets/images/products/6.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 7,
    title: "tag to wear",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now"],
    brand: null,
    images: [require("../assets/images/products/7.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 8,
    title: "tag to wear",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now"],
    brand: null,
    images: [require("../assets/images/products/1.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 9,
    title: "tag to wear",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["featured product", "trending now"],
    brand: null,
    images: [require("../assets/images/products/1.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
  {
    id: 10,
    title: "tag to wear",
    price: 200,
    discount: 20,
    del: 287,
    seller: "by mango",
    category: "men",
    tag: ["trending now", "top picks"],
    brand: null,
    images: [require("../assets/images/products/1.jpg")],
    variants: [],
    specification: "",
    features: "",
    product_reviews: [],
    product_code: "460356366_floral",
    product_details:
      "Black, off-white and peach-coloured printed flared skirt, has zip closure, attached lining",
  },
];

export default data;
